config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.cinnamon_scrappy_dragonfly.sh
        container: qc.acc_zinnia_forgiving_okapi
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grege_quirky_phoenix.sh
        container: qc.doc_viridian_adaptable_kirin
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.echelon_mindful_tapir.sh
        container: qc.doc_incarnadine_impulsive_pelican
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sand_stubborn_panther.sh
        container: qc.doc_celadon_independent_eel
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.burgundy_exuberant_serval.sh
        container: qc.lic_cerise_methodical_hyena
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ruby_shy_opossum.sh
        container: qc.sec_ginger_cranky_hawk
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tide_skeptical_skunk.sh
        container: qc.sty_tan_lively_cougar
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.mulberry_optimistic_armadillo.sh
        container: qc.sty_persimmon_determined_newt
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.silver_practical_dormouse.sh
        container: qc.uni_orchid_reserved_nymph
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ochre_eager_okapi.sh
        container: qc.ver_lemon_industrious_lobster
timeout: 5400
