config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.incarnadine_audacious_porcupine.sh
        container: qc.acc_sienna_candid_horse
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.champagne_silly_manta.sh
        container: qc.doc_red_blissful_pelican
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.periwinkle_pensive_falcon.sh
        container: qc.doc_alabaster_affectionate_angelfish
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_generous_manta.sh
        container: qc.doc_ebony_friendly_gorilla
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wine_patient_buffalo.sh
        container: qc.lic_thistle_passionate_chinchilla
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.celadon_radiant_phoenix.sh
        container: qc.sec_tangerine_honest_jaguar
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks flake8:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_compassionate_catfish.sh
        container: qc.sty_jasmine_sincere_platypus
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.polar_focused_kraken.sh
        container: qc.sty_royal_timid_badger
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.violet_polite_quokka.sh
        container: qc.uni_tide_authentic_rattlesnake
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.coffee_adaptable_platypus.sh
        container: qc.ver_thunder_humorous_hummingbird
timeout: 5400
