config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_supportive_tarantula.sh
        container: qc.acc_banana_mysterious_pegasus
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.carmine_respectful_ibis.sh
        container: qc.doc_zinnia_amiable_gecko
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.linen_peppy_hyena.sh
        container: qc.doc_hunter_nurturing_spren
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flint_determined_butterfly.sh
        container: qc.doc_puce_sincere_grasshopper
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_generous_seahorse.sh
        container: qc.lic_ultramarine_rugged_groundhog
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.denim_radiant_wolverine.sh
        container: qc.sec_wine_ambitious_bullfrog
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks flake8:
        commands:
        - /usr/bin/env sh .sqa/script.banana_brave_pelican.sh
        container: qc.sty_tide_spirited_moose
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.cyan_driven_ibis.sh
        container: qc.sty_currant_pensive_buffalo
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.amaranth_creative_coyote.sh
        container: qc.uni_pineapple_industrious_reindeer
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.coffee_empathetic_echidna.sh
        container: qc.ver_yellow_innocent_eagle
timeout: 5400
